- name: Install Nginx on CentOS/RHEL
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  tasks:
    - name: Install Nginx
      command: dnf install -y nginx --setopt=module_platform_id=
      environment:
        ANSIBLE_BECOME_PASS: "votre_mot_de_passe_sudo"
