- name: Install Nginx on CentOS/RHEL
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
    YUM_FLAGS: "module_platform_id='' module_hotfixes=1"
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present
      environment:
        YUM_FLAGS: "{{ YUM_FLAGS }}"
