- name: Update all packages and install Nginx on Ubuntu
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.7
  tasks:
    - name: Update all packages
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present
