- name: Install Nginx on CentOS/RHEL
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  tasks:
    - name: Install Nginx
      command: dnf install -y nginx
      warn: no  # Pour supprimer le message d'avertissement
      environment:
        DNF_FLAGS: "module_platform_id='' module_hotfixes=1"
