- name: Install Nginx on CentOS/RHEL
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      dnf:
        name: nginx
        state: present

    - name: Enable dnf module filtering for Nginx
      shell: mv /etc/dnf/dnf.conf /etc/dnf/dnf.conf.tmp
      args:
        warn: no
