- name: Install Nginx on CentOS/RHEL
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  tasks:
    - name: Install Nginx
      dnf:
        name: nginx
        state: present
    - name: Disable dnf module filtering for Nginx
      copy:
        content: |
          [main]
          enabled=1
          gpgcheck=1
          [nginx]
          enabled=0
        dest: /etc/dnf/dnf.conf.tmp
    - name: Move dnf config file back
      shell: mv /etc/dnf/dnf.conf.tmp /etc/dnf/dnf.conf
      args:
        warn: no
