- name: Update all packages and install Nginx on ubuntu
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
  tasks:
#    - name: Update all packages
 #     apt:
  #      name: '*'
   #     state: latest
    - name: Install Nginx
      apt:
        name: nginx
        state: present
